# Generated by Django 6.0.6 on 2026-06-20 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_booking_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='mentor',
            name='company',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='mentor',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='mentor',
            name='price',
            field=models.PositiveIntegerField(default=0, help_text='Session price in Naira'),
        ),
        migrations.AddField(
            model_name='mentor',
            name='rating',
            field=models.DecimalField(decimal_places=1, default=4.5, max_digits=2),
        ),
        migrations.AddField(
            model_name='mentor',
            name='reviews',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='mentor',
            name='expertise',
            field=models.CharField(max_length=150),
        ),
    ]
