# Generated by Django 6.0.6 on 2026-06-20 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0004_mentor_company_mentor_is_featured_mentor_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mentor',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='mentors/'),
        ),
        migrations.AlterField(
            model_name='mentor',
            name='price',
            field=models.PositiveIntegerField(default=0, help_text='Session price in Dollars'),
        ),
    ]
