# Generated by Django 6.0.6 on 2026-06-21 02:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0005_alter_mentor_image_alter_mentor_price'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=20)),
                ('field', models.CharField(choices=[('Software Engineering', 'Software Engineering'), ('AI', 'AI'), ('Cybersecurity', 'Cybersecurity'), ('UI/UX', 'UI/UX'), ('Data Science', 'Data Science'), ('Cloud Computing', 'Cloud Computing')], max_length=50)),
                ('goal', models.CharField(choices=[('Get Internship', 'Get Internship'), ('Build Startup', 'Build Startup'), ('Learn New Skill', 'Learn New Skill'), ('Career Growth', 'Career Growth')], max_length=50)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
