# Generated by Django 6.0.6 on 2026-06-21 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0006_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('declined', 'Declined'), ('Pending', 'Pending'), ('Confirmed', 'Confirmed'), ('Declined', 'Declined')], default='pending', max_length=10),
        ),
    ]
