# Generated by Django 6.0.6 on 2026-06-21 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0007_alter_booking_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='admin_note',
            field=models.TextField(blank=True, help_text='Optional note from admin when confirming, declining or refunding', null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='payment_status',
            field=models.CharField(choices=[('Unpaid', 'Unpaid'), ('Paid', 'Paid'), ('Refunded', 'Refunded')], default='Unpaid', max_length=20),
        ),
        migrations.AddField(
            model_name='booking',
            name='reason',
            field=models.TextField(blank=True, help_text='Reason for booking this mentorship session', null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Confirmed', 'Confirmed'), ('Declined', 'Declined'), ('Completed', 'Completed'), ('Refunded', 'Refunded')], default='Pending', max_length=20),
        ),
    ]
